spring:
    datasource:
        name: h5perf
        url: jdbc:mysql://localhost:3306/h5perf?autoReconnect=true&useSSL=false
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver

    mvc:
    # 所有的访问都匹配映射到静态资源路径,spring.mvc.static-path-pattern 只可以定义一个，目前不支持多个逗号分割的方式
        static-path-pattern: /**

    resources:
    # 这里的配置是覆盖默认配置，所以需要将默认的也加上否则static、public等这些路径将不能被当作静态资源路径
        static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/

    # 在freemarker获取request对象
    freemarker:
        request-context-attribute: request

mybatis:
    type-aliases-package: com.easy.springboot.h5perf.model
    configuration:
        # 开启mybatis开启数据库字段自动映射驼峰命名规则java属性
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30



pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


#mapper:
#    mappers:
#        - com.easy.springboot.h5perf.mapper.TestCaseMapper
#        - com.easy.springboot.h5perf.mapper.TestResourceMapper
#        - com.easy.springboot.h5perf.mapper.TestTimeDataMapper
#    not-empty: false
#    identity: MYSQL


logging:
    level:
      root: WARN
      com:
        easy:
          springboot:
            h5perf:
              mapper: TRACE

server:
    port: 8188

#debug:
#    true
