spring:
    datasource:
        name: h5perf
        url: jdbc:mysql://localhost:3306/h5perf?autoReconnect=true&useSSL=false
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver

    mvc:
        static-path-pattern: /static/**

    resources:
        static-locations: classpath:/static/

    # 在freemarker获取request对象
    freemarker:
        request-context-attribute: request

mybatis:
    type-aliases-package: com.easy.springboot.h5perf.model
    configuration:
        # 开启mybatis开启数据库字段自动映射驼峰命名规则java属性
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30


logging:
    level:
      root: WARN
      com:
        easy:
          springboot:
            h5perf:
              mapper: TRACE

server:
    port: 8188

debug:
    true
